services:
  frontend:
    build:
      context: frontend/
      args:
        BACKEND_HOST: backend:8000
        NGINX_CONF: nginx.local.conf
    ports:
      - "5000:5000"
    depends_on:
      - backend
    # command: ["sh", "-c", "sleep infinity"]

  backend:
    build: backend/
    working_dir: /app
    ports:
      - "8000:8000"
    command: ["uv", "run", "-m", "eshop_inventory.app"]
    environment:
      - ENVIRONMENT=local
      - API_TOKEN=${API_TOKEN}  # from .env file
      - BACKEND_PORT=8000
